"""add_team_members_and_extend_teams

Revision ID: 51a6a3d0a092
Revises: 9a5837c2b39e
Create Date: 2026-06-09 00:45:36.581248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a6a3d0a092'
down_revision: Union[str, Sequence[str], None] = '9a5837c2b39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'telegram_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_telegram_id'), 'team_members', ['telegram_id'], unique=False)

    # Добавляем колонки как nullable, заполняем существующие строки, затем делаем NOT NULL
    op.add_column('teams', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('teams', sa.Column('owner_telegram_id', sa.BigInteger(), nullable=True))
    op.execute("UPDATE teams SET name = 'Team-' || chat_id WHERE name IS NULL")
    op.execute("UPDATE teams SET owner_telegram_id = 0 WHERE owner_telegram_id IS NULL")
    op.alter_column('teams', 'name', nullable=False)
    op.alter_column('teams', 'owner_telegram_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'owner_telegram_id')
    op.drop_column('teams', 'name')
    op.drop_index(op.f('ix_team_members_telegram_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###
