"""rename_telemost_to_meeting_url

Revision ID: 769f1c512b8a
Revises: f7d8e9a0b1c2
Create Date: 2026-06-08 22:07:11.555307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769f1c512b8a'
down_revision: Union[str, Sequence[str], None] = 'f7d8e9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
