"""add yougile_user_aliases

Revision ID: 87b605b5ec3c
Revises: b4c5d6e7f8a9
Create Date: 2026-06-13 13:21:48.665755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b605b5ec3c'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('task_title', sa.String(length=256), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_tasks_team_id'), 'pending_tasks', ['team_id'], unique=False)
    op.create_table('yougile_user_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('yougile_user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'alias', name='uq_yougile_alias')
    )
    op.create_index(op.f('ix_yougile_user_aliases_team_id'), 'yougile_user_aliases', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yougile_user_aliases_team_id'), table_name='yougile_user_aliases')
    op.drop_table('yougile_user_aliases')
    op.drop_index(op.f('ix_pending_tasks_team_id'), table_name='pending_tasks')
    op.drop_table('pending_tasks')
    # ### end Alembic commands ###
