"""add message_risks

Revision ID: a91d3f584fbe
Revises: d4e5f6a7b8c9
Create Date: 2026-06-12 00:19:40.063431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91d3f584fbe'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_risks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=False),
    sa.Column('yougile_task_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_risks_created_at'), 'message_risks', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_risks_team_id'), 'message_risks', ['team_id'], unique=False)
    op.create_index(op.f('ix_message_risks_user_id'), 'message_risks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_risks_user_id'), table_name='message_risks')
    op.drop_index(op.f('ix_message_risks_team_id'), table_name='message_risks')
    op.drop_index(op.f('ix_message_risks_created_at'), table_name='message_risks')
    op.drop_table('message_risks')
    # ### end Alembic commands ###
