"""add last_reminded_at to commitments

Revision ID: ab3faac53e22
Revises: c40e205dba86
Create Date: 2026-06-09 00:19:50.489468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3faac53e22'
down_revision: Union[str, Sequence[str], None] = 'c40e205dba86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('last_reminded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'last_reminded_at')
    # ### end Alembic commands ###
