"""initial

Revision ID: acfcc20c61e9
Revises: 
Create Date: 2026-06-06 21:39:12.548727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfcc20c61e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_cache',
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('key_enc', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_api_key_user_provider')
    )
    op.create_table('auto_reply_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_name', sa.String(length=256), nullable=True),
    sa.Column('incoming_text', sa.Text(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_reply_logs_created_at'), 'auto_reply_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_auto_reply_logs_peer_id'), 'auto_reply_logs', ['peer_id'], unique=False)
    op.create_index(op.f('ix_auto_reply_logs_user_id'), 'auto_reply_logs', ['user_id'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_name', sa.String(length=256), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_peer_id'), 'commitments', ['peer_id'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_kind', sa.String(length=16), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_news_source', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('style_profile', sa.JSON(), nullable=True),
    sa.Column('style_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'peer_id', name='uq_contact_user_peer')
    )
    op.create_index(op.f('ix_contacts_peer_id'), 'contacts', ['peer_id'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('index_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('last_indexed_message_id', sa.BigInteger(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'peer_id', name='uq_index_user_peer')
    )
    op.create_index(op.f('ix_index_jobs_peer_id'), 'index_jobs', ['peer_id'], unique=False)
    op.create_index(op.f('ix_index_jobs_user_id'), 'index_jobs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(length=256), nullable=True),
    sa.Column('is_outgoing', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('media_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('indexed_in_vector', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'peer_id', 'message_id', name='uq_msg_user_peer_id')
    )
    op.create_index(op.f('ix_messages_date'), 'messages', ['date'], unique=False)
    op.create_index(op.f('ix_messages_peer_id'), 'messages', ['peer_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index('ix_messages_user_peer_date', 'messages', ['user_id', 'peer_id', 'date'], unique=False)
    op.create_table('news_topics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_topics_user_id'), 'news_topics', ['user_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_user_id'), 'pending_actions', ['user_id'], unique=False)
    op.create_table('telegram_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('api_hash_enc', sa.Text(), nullable=False),
    sa.Column('session_string_enc', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=16), nullable=False),
    sa.Column('use_heavy_model', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('digest_time', sa.String(length=5), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('transcription_mode', sa.String(length=16), nullable=False),
    sa.Column('auto_reply_cooldown_min', sa.Integer(), nullable=False),
    sa.Column('auto_reply_mode', sa.String(length=8), nullable=False),
    sa.Column('auto_reply_text', sa.Text(), nullable=False),
    sa.Column('ignore_archived', sa.Boolean(), nullable=False),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_lead_hours', sa.Integer(), nullable=False),
    sa.Column('reminder_overdue_enabled', sa.Boolean(), nullable=False),
    sa.Column('news_enabled', sa.Boolean(), nullable=False),
    sa.Column('news_window_hours', sa.Integer(), nullable=False),
    sa.Column('news_digest_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('telegram_sessions')
    op.drop_index(op.f('ix_pending_actions_user_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_news_topics_user_id'), table_name='news_topics')
    op.drop_table('news_topics')
    op.drop_index('ix_messages_user_peer_date', table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_peer_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_date'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_index_jobs_user_id'), table_name='index_jobs')
    op.drop_index(op.f('ix_index_jobs_peer_id'), table_name='index_jobs')
    op.drop_table('index_jobs')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_peer_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_peer_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_auto_reply_logs_user_id'), table_name='auto_reply_logs')
    op.drop_index(op.f('ix_auto_reply_logs_peer_id'), table_name='auto_reply_logs')
    op.drop_index(op.f('ix_auto_reply_logs_created_at'), table_name='auto_reply_logs')
    op.drop_table('auto_reply_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('transcription_cache')
    # ### end Alembic commands ###
