"""add platform column to meetings

Revision ID: c40e205dba86
Revises: 769f1c512b8a
Create Date: 2026-06-08 22:42:41.600335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40e205dba86'
down_revision: Union[str, Sequence[str], None] = '769f1c512b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('platform', sa.String(length=32), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'platform')
    # ### end Alembic commands ###
