"""add pending_team_tasks

Revision ID: d2854d2a3417
Revises: a91d3f584fbe
Create Date: 2026-06-12 16:13:28.989253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2854d2a3417'
down_revision: Union[str, Sequence[str], None] = 'a91d3f584fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_team_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('yougile_task_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_team_tasks_assignee_telegram_id'), 'pending_team_tasks', ['assignee_telegram_id'], unique=False)
    op.create_index(op.f('ix_pending_team_tasks_team_id'), 'pending_team_tasks', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_team_tasks_team_id'), table_name='pending_team_tasks')
    op.drop_index(op.f('ix_pending_team_tasks_assignee_telegram_id'), table_name='pending_team_tasks')
    op.drop_table('pending_team_tasks')
    # ### end Alembic commands ###
