"""add_display_name_to_user_and_yougile_id_to_team_member

Revision ID: dc0d391b3de9
Revises: b1c2d3e4f5a6
Create Date: 2026-06-11 01:01:50.811550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0d391b3de9'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_mtslink_record_id'), table_name='meetings')
    op.add_column('team_members', sa.Column('yougile_user_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=128), nullable=True))
    op.execute("UPDATE users SET display_name = '' WHERE display_name IS NULL")
    op.alter_column('users', 'display_name', nullable=False, server_default='')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('team_members', 'yougile_user_id')
    op.create_index(op.f('ix_meetings_mtslink_record_id'), 'meetings', ['mtslink_record_id'], unique=False)
    # ### end Alembic commands ###
