"""add active_board to teams

Revision ID: e570f9fd76ac
Revises: 51a6a3d0a092
Create Date: 2026-06-09 16:45:11.503220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e570f9fd76ac'
down_revision: Union[str, Sequence[str], None] = '51a6a3d0a092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('active_board_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('active_board_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'active_board_name')
    op.drop_column('teams', 'active_board_id')
    # ### end Alembic commands ###
