"""add_meeting_tables

Revision ID: ecc8a2de13a1
Revises: 5505afa5475e
Create Date: 2026-06-07 15:10:22.635393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc8a2de13a1'
down_revision: Union[str, Sequence[str], None] = '5505afa5475e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('telemost_url', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_team_id'), 'meetings', ['team_id'], unique=False)
    op.create_table('meeting_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_name', sa.String(length=128), nullable=True),
    sa.Column('assignee_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('created_in_kanban', sa.Boolean(), nullable=False),
    sa.Column('kanban_card_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_tasks_meeting_id'), 'meeting_tasks', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_tasks_meeting_id'), table_name='meeting_tasks')
    op.drop_table('meeting_tasks')
    op.drop_index(op.f('ix_meetings_team_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
